backend:
  name: github
  repo: wkreative/orkiosk-next
  branch: main
  base_url: https://us-central1-orkiosk-web.cloudfunctions.net/oauth
  auth_endpoint: auth

site_url: https://orkiosk.com

media_folder: "public/uploads"
public_folder: "/uploads"
publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Extracto", name: "excerpt", widget: "text" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Autor", name: "author", widget: "string" }
      - { label: "Categoria", name: "category", widget: "string" }
      - { label: "Contenido", name: "body", widget: "markdown" }
