backend:
  name: github
  repo: wkreative/orkiosk-next
  branch: main
  base_url: https://us-central1-orkiosk-web.cloudfunctions.net
  auth_endpoint: /oauth/auth

site_url: https://orkiosk-web.web.app

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Articulos"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titulo", name: "title", widget: "string", required: true }
      - { label: "Excerpt", name: "excerpt", widget: "text", required: true }
      - { label: "Fecha", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false, required: true }
      - { label: "Autor", name: "author", widget: "string", required: false }
      - { label: "Categoria", name: "category", widget: "select", options: ["Transformacion Digital", "Restaurantes", "Retail", "Optimizacion", "Noticias"], required: false }
      - { label: "Imagen Destacada", name: "image", widget: "image", required: false }
      - { label: "Contenido", name: "body", widget: "markdown", required: true }

  - name: "home"
    label: "Pagina Principal"
    folder: "content/home"
    create: false
    fields:
      - { label: "Titulo Hero", name: "hero_title", widget: "string", required: false }
      - { label: "Subtitulo Hero", name: "hero_subtitle", widget: "text", required: false }
